#!/bin/bash

# Get current datetime in readable format (YYYY-MM-DD_HH-MM-SS)
DATETIME=$(date +"%Y-%m-%d_%H-%M-%S")
OUTPUT_DIR="logs/likelihood_analysis_${DATETIME}"

# Create output directory
mkdir -p "${OUTPUT_DIR}"

# Run the likelihood analysis script
echo "Starting LLaDA likelihood analysis..."
echo "Output directory: ${OUTPUT_DIR}"
echo "=================================="

CUDA_VISIBLE_DEVICES=3,2 uv run -m dquantize.run_llada_likelihood_analysis \
    --model "GSAI-ML/LLaDA-8B-Instruct" \
    --quantized_model "/home/scratch/hshah2/dquantize_cache/GSAI-ML/LLaDA-8B-Instruct-w4-g128.pt" \
    --dataset "wikitext2" \
    --max_examples 128 \
    --min_length 32 \
    --max_length 128 \
    --output_dir "${OUTPUT_DIR}" \
    --steps 32 \
    --gen_length 128 \
    --block_length 32 \
    --temperature 0. \
    --cfg_scale 0. \
    --batch_size 8 \
    --mc_num 100 \
    --mc_batch_size 10 | tee "${OUTPUT_DIR}/run_log.txt"

echo "=================================="
echo "Likelihood analysis complete!"
echo "Results saved to: ${OUTPUT_DIR}"
echo ""
echo "Output files:"
echo "  - ${OUTPUT_DIR}/likelihood_analysis.jsonl    (detailed log-likelihood per sample)"
echo "  - ${OUTPUT_DIR}/likelihood_summary.json      (summary statistics)"
echo "  - ${OUTPUT_DIR}/generated_text.jsonl         (text generated by precise model)"
echo "  - ${OUTPUT_DIR}/likelihood_config.yaml       (configuration used)"
echo "  - ${OUTPUT_DIR}/run_log.txt                  (console output log)"